version: '3.9'
services:
  penx_web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-nextauth-secret
        DATABASE_URL: your-database-url
        REDIS_URL: your
        NEXT_PUBLIC_DEPLOY_MODE: SELF_HOSTED
        SELF_HOSTED_CREDENTIALS: your-self-hosted-credentials
    container_name: penx_web
    ports:
      - '3000:3000'
